#!/usr/bin/env ruby
require 'json'
require 'yaml'

dir = File.dirname(File.expand_path(__FILE__))
require "#{dir}/include.rb"

class DupConfig
    def initialize(argv)
        @format = :json
        @keyPath = []
        if argv.length > 0
            if argv.last[0] != '-'
                @keyPath = argv.last.split('.')
            end

            if argv.include? '--json'
                @format = :json
            elsif argv.include? '--yaml'
                @format = :yaml
            end
        end
    end

    def fetch
        configuration = getConfig()
        @keyPath.inject(configuration) {|acc, value| acc[value]}
    end

    def main
        value = fetch()

        if value.nil?
            # Do nothing for nil

        elsif value.kind_of? String # Directly print scalar types
            puts value
        elsif value.is_a? Numeric
            puts value
        else
            # Format any other output
            case @format
                when :json
                    puts fetch().to_json

                when :yaml
                    puts fetch().to_yaml
            end
        end
    end
end

app = DupConfig.new(ARGV)

app.main()
