scripts:
    ENV:
        MYSQL_ROOT_PASSWORD: "3FwDkQ6gGeVVYDkES3H95auCVekAnG"
        MYSQL_USER: "client"
        MYSQL_DATABASE: "client"
        MYSQL_PASSWORD: "R77bm8pYNkNfSGBf2z2McNxHazR45Z"

        TYPO3_INSTALL: true
        TYPO3_SITE_ENV: DEV
        TYPO3_CLIENT_INSTALL: true
        TYPO3_DOWNLOAD_FORCE: false

        DUP_BASE: "dup"

packages:
    - apache

    - mariadb

    - graphicsmagick
    - php-fpm
    - php-gd
    - php-mcrypt
    - php-intl

services:
    - php-fpm.service
    - httpd.service
    - mysqld.service
