scripts:
    ENV:
        DB_ROOT_PASSWORD: "3FwDkQ6gGeVVYDkES3H95auCVekAnG"
        DB_HOST: "localhost"
        DB_USERNAME: "client"
        DB_NAME: "client"
        DB_PASSWORD: "R77bm8pYNkNfSGBf2z2McNxHazR45Z"

        TYPO3_INSTALL: true
        TYPO3_SITE_ENV: DEV

        TYPO3_CLIENT_INSTALL: true
        TYPO3_CLIENT_BRANCH: feature/typo3-7-lts
        TYPO3_DOWNLOAD_FORCE: false

        DUP_BASE: "dup"

packages:
    - apache

    - mariadb

    - graphicsmagick
    - openssl
    - php-fpm
    - php-gd
    - php-mcrypt
    - php-intl

php:
    features:
        opcache: true
    ini:
        always_populate_raw_post_data: -1
        max_execution_time: 240
        max_input_vars: 1500
        date.timezone: Europe/Vaduz
        display_errors: on
        display_startup_errors: on
        error_reporting: 32767

services:
    - php-fpm.service
    - httpd.service
    - mysqld.service
